### ISSUE TITLE
Display progress

### ISSUE THREAD

**Issue by gigawatts** [caveman99/Meshtastic-Wiphone#2]
I just ran into your repo recently and used it to successfully build the latest Meshtastic firmware to run on my WiPhone. Thanks for the example!

I'm curious if you have made any further progress, such as getting the TFT Display and Keypad working?

I took a shot at it myself today, using the [T-Deck variant](https://github.com/meshtastic/firmware/tree/master/variants/t-deck) and [T-Watch variant](https://github.com/meshtastic/firmware/blob/master/variants/t-watch-s3/variant.h) as examples (they both use the same ST7789 Display Driver as the WiPhone), but no luck so far, it seems I've run out of available RAM on the ESP32 (see below for compiler errors). I also need to figure out how to enable support for the GPIO Expander used in the WiPhone.

I can share what I've tried so far, if you want to collaborate on this.

```
xtensa-esp32-elf/bin/ld: .pio/build/wiphone/firmware.elf section `.iram0.text' will not fit in region `iram0_0_seg'
xtensa-esp32-elf/bin/ld: IRAM0 segment data does not fit.
xtensa-esp32-elf/bin/ld: region `iram0_0_seg' overflowed by 2740 bytes
```

**Comment by caveman99** [comment]
The Project is on the backlog for me since there are more modern (and cheaper) options available. Remaining issues are indeed the GPIO expander (matrix keypad support was recently added to the main firmware) and the screen. If we get a kind of complete support working, i am going to move this into the main meshtatic firmware repository as a variant, but again i don't have the capacity or incentive to do it myself
